fix: add rotate and step additonal checks + use custom errors for gas…
ChainSafe/spectre-contracts pull request #3
Opened 2024-03-13 15:30 UTC by nmlinaric

This PR adds:
- check for rotate and step (if value is already save revert with Error)
- removes unused `head` const
- replaces `require` statements with custom errors to save on gas

2024-03-13 15:36 UTC, nulltea requested changes

2024-03-13 15:36 UTC, nulltea commented on src/Spectre.sol
> +        if (_syncCommitteePoseidon == syncCommitteePoseidon) revert InvalidSyncComitee();
```suggestion
        if (_syncCommitteePoseidon != syncCommitteePoseidon) revert InvalidSyncComitee();
```

2024-03-13 15:36 UTC, nulltea commented on src/Spectre.sol
> +        if (_publicInputsCommitment == publicInputsCommitment) revert InvalidPublicInputsCommitment();
```suggestion
        if (_publicInputsCommitment != publicInputsCommitment) revert InvalidPublicInputsCommitment();
```

2024-03-14 06:20 UTC, lastperson requested changes
Shouldn't there be tests for of the reverts?

2024-03-14 06:20 UTC, lastperson commented on src/Spectre.sol
> +        if (syncCommitteePoseidons[attestingPeriod] != 0) revert SyncCommiteeNotYetSetForPeriod();
```suggestion
        if (syncCommitteePoseidons[attestingPeriod] == 0) revert SyncCommiteeNotYetSetForPeriod();
```

2024-03-14 11:32 UTC, nmlinaric commented
> Shouldn't there be tests for of the reverts?

I'll add them in the following days, wanted to confirm if all the checks logic is valid.

2024-03-14 16:24 UTC, nulltea approved these changes

2024-03-15 07:29 UTC, lastperson approved these changes

2024-04-04 09:09 UTC, merged